#!/bin/bash
journalctl -b -f -n 0 -o json | /infometis/journalctl/output-to-log 1

# put in directory /infometis/journalctl
# create /infometis/journalctl/data for log files
# create symlink in /etc/systemctl/system for journalctl.output-to-log.server
# set 744 permissions on all files
