boot/shutdown,ekg,ekg,ekg
start/stop,ekg,ekg,ekg_rest_elasticsearch
start/stop,ekg,ekg,ekg_ui_grafana
start/stop,ekg,ekg,ekg_ui_kibana
start/stop,ingest_journal,ingest_logs,ingest_logs
boot/shutdown,ksqldb,ksqldb,ksqldb
start/stop,ksqldb,ksqldb,ksqldb_rest_ksql_server
boot/shutdown,ksqldb,ksqldb_dev,ksqldb_dev
start/stop,ksqldb,ksqldb_dev,ksqldb_dev_rest_ksql_server
boot/shutdown,kz,kz,kz
start/stop,metrics_node,metrics_node,metrics_node
start/stop,metrics_overlay,metrics_overlay,metrics_overlay
boot/shutdown,schema_registry,schema_registry,schema_registry
start/stop,schema_registry,schema_registry,schema_registry_ext_rest
boot/shutdown,streamsets,export,export
start/stop,streamsets,export,export_ui_streamsets

